blank_issues_enabled: false
contact_links:
    - name: Vencord Support Server
      url: https://discord.gg/D9uwnFnqmd
      about: If you need help regarding Vesktop or Vencord, please join our support server!
